-- Ejecutar desde PostgreSQL despues de crear la base de datos.
-- Tablas en esquema clean.

CREATE TABLE IF NOT EXISTS clean.pobreza_clean (
    numren bigint,
    sexo bigint,
    edad bigint,
    folio bigint,
    tam_loc bigint,
    est_dis bigint,
    upm bigint,
    factor bigint,
    ur_rur_2500 bigint,
    municipio bigint,
    entidad bigint,
    ccevj double precision,
    cbdj double precision,
    csj double precision,
    ctelj double precision,
    cenj double precision,
    rei double precision,
    ett double precision,
    casi double precision,
    cassi double precision,
    cyt double precision,
    nbi double precision,
    mmip double precision,
    e_ccevj bigint,
    e_cbdj bigint,
    e_csj bigint,
    e_ctelj bigint,
    e_cenj bigint,
    e_rei bigint,
    e_cassi bigint,
    e_casi bigint,
    e_nbi bigint,
    e_cict bigint,
    e_ett bigint,
    e_cyt bigint,
    e_mmip bigint,
    anio integer,
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    tiempo_id integer
);

CREATE TABLE IF NOT EXISTS clean.infraestructura_clean (
    cve_ent integer,
    alcaldia text,
    cve_col text,
    colonia text,
    ba1_noeqsa bigint,
    ba1_c_noeq bigint,
    ba8_nomerc bigint,
    ba8_noloca bigint,
    ba8_ci_nom bigint,
    ba8_ci_loc bigint,
    ba8_s_merc bigint,
    ba8_c_merc bigint,
    ba9_no_gua bigint,
    ba9_c_no_g bigint,
    ba3_noeqed bigint,
    ba3_diseqb double precision,
    ba3_ci_eqe bigint,
    ba3_ci_dis bigint,
    ba3_s_eqed bigint,
    ba3_c_eqed bigint,
    p_porcelec double precision,
    r_valelect bigint,
    p_aguapot double precision,
    r_val_dren bigint,
    epr_pob double precision,
    r_epr_pob bigint,
    resid_ton double precision,
    r_resd_ton bigint,
    alump_sum bigint,
    alump_mean double precision,
    r_alump_su bigint,
    r_alump_mn bigint,
    s_ri_6 bigint,
    c_ri_6 bigint,
    id bigint,
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    colonia_key text,
    colonia_nombre text,
    infraestructura_actualizacion_anio integer,
    infraestructura_es_snapshot boolean,
    infraestructura_temporalidad text,
    infraestructura_uso_recomendado text
);

CREATE TABLE IF NOT EXISTS clean.fgj_clean (
    fecha_hecho date,
    fecha_inicio date,
    anio_hecho_clean bigint,
    mes_hecho_clean bigint,
    delito text,
    delito_key text,
    categoria_delito text,
    alcaldia_key text,
    alcaldia_nombre text,
    colonia_key text,
    colonia_hecho text,
    latitud double precision,
    longitud double precision,
    subtipo_robo_patrimonial text,
    is_robo_patrimonial integer
);
