-- Ejecutar desde PostgreSQL despues de crear la base de datos.
-- Tablas en esquema analytics.

CREATE TABLE IF NOT EXISTS analytics.pobreza_alcaldia_anio (
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    anio integer,
    tiempo_id integer,
    n_registros_sociales integer,
    factor_sum bigint,
    mmip_wmean double precision,
    rei_wmean double precision,
    nbi_wmean double precision,
    ccevj_wmean double precision,
    cbdj_wmean double precision,
    csj_wmean double precision,
    ctelj_wmean double precision,
    cenj_wmean double precision,
    ett_wmean double precision,
    casi_wmean double precision,
    cassi_wmean double precision,
    cyt_wmean double precision
);

CREATE TABLE IF NOT EXISTS analytics.infraestructura_alcaldia (
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    colonias_count bigint,
    infraestructura_actualizacion_anio integer,
    infraestructura_es_snapshot boolean,
    infraestructura_temporalidad text,
    infraestructura_uso_recomendado text,
    ba1_noeqsa_sum bigint,
    ba8_nomerc_sum bigint,
    ba8_noloca_sum bigint,
    ba9_no_gua_sum bigint,
    ba3_noeqed_sum bigint,
    resid_ton_sum bigint,
    alump_sum_total bigint,
    p_porcelec_avg double precision,
    r_valelect_avg double precision,
    p_aguapot_avg double precision,
    r_val_dren_avg double precision,
    epr_pob_avg double precision,
    r_epr_pob_avg double precision,
    r_resd_ton_avg double precision,
    alump_mean_avg double precision,
    r_alump_su_avg double precision,
    r_alump_mn_avg double precision,
    s_ri_6_avg double precision,
    c_ri_6_avg double precision,
    mercados_total bigint,
    locales_total bigint,
    iluminacion_total bigint,
    iluminacion_promedio double precision,
    residuos_ton_total bigint,
    equipamiento_salud_total bigint,
    equipamiento_educativo_total bigint,
    agua_potable_promedio double precision,
    electricidad_promedio double precision,
    drenaje_promedio double precision
);

CREATE TABLE IF NOT EXISTS analytics.delitos_alcaldia_anio (
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    anio integer,
    tiempo_id integer,
    total_delitos_fgj bigint,
    total_robos_patrimoniales bigint,
    total_no_robos_patrimoniales bigint,
    share_robos_patrimoniales_sobre_total_delitos double precision
);

CREATE TABLE IF NOT EXISTS analytics.fgj_robos_patrimoniales_clean (
    fecha_hecho date,
    fecha_inicio date,
    anio_hecho_clean bigint,
    mes_hecho_clean bigint,
    delito text,
    delito_key text,
    categoria_delito text,
    alcaldia_key text,
    alcaldia_nombre text,
    colonia_key text,
    colonia_hecho text,
    latitud double precision,
    longitud double precision,
    subtipo_robo_patrimonial text,
    is_robo_patrimonial integer
);

CREATE TABLE IF NOT EXISTS analytics.robos_patrimoniales_alcaldia_mes_subtipo (
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    anio integer,
    mes integer,
    tiempo_id integer,
    subtipo_robo_patrimonial text,
    total_robos_patrimoniales bigint,
    registros_con_coordenadas integer,
    latitud_promedio double precision,
    longitud_promedio double precision
);

CREATE TABLE IF NOT EXISTS analytics.robos_patrimoniales_alcaldia_anio (
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    anio integer,
    tiempo_id integer,
    target_robos_patrimoniales_total bigint,
    robo_a_transeunte bigint,
    robo_a_negocio bigint,
    robo_a_casa_habitacion bigint,
    robo_de_vehiculo bigint,
    robo_de_accesorios_auto bigint,
    robo_del_interior_de_vehiculo bigint,
    target_robos_log1p double precision
);

CREATE TABLE IF NOT EXISTS analytics.panel_alcaldia_anio (
    alcaldia_key text,
    alcaldia_nombre text,
    alcaldia_id integer,
    anio integer,
    tiempo_id integer,
    n_registros_sociales integer,
    factor_sum bigint,
    mmip_wmean double precision,
    rei_wmean double precision,
    nbi_wmean double precision,
    ccevj_wmean double precision,
    cbdj_wmean double precision,
    csj_wmean double precision,
    ctelj_wmean double precision,
    cenj_wmean double precision,
    ett_wmean double precision,
    casi_wmean double precision,
    cassi_wmean double precision,
    cyt_wmean double precision,
    total_delitos_fgj bigint,
    share_robos_patrimoniales_sobre_total_delitos double precision,
    target_robos_patrimoniales_total bigint,
    robo_a_transeunte bigint,
    robo_a_negocio bigint,
    robo_a_casa_habitacion bigint,
    robo_de_vehiculo bigint,
    robo_de_accesorios_auto bigint,
    robo_del_interior_de_vehiculo bigint,
    target_robos_log1p double precision,
    share_robo_a_transeunte double precision,
    share_robo_a_negocio double precision,
    share_robo_a_casa_habitacion double precision,
    share_robo_de_vehiculo double precision,
    share_robo_de_accesorios_auto double precision,
    share_robo_del_interior_de_vehiculo double precision,
    colonias_count bigint,
    mercados_total bigint,
    locales_total bigint,
    iluminacion_total bigint,
    iluminacion_promedio double precision,
    residuos_ton_total bigint,
    equipamiento_salud_total bigint,
    equipamiento_educativo_total bigint,
    agua_potable_promedio double precision,
    electricidad_promedio double precision,
    drenaje_promedio double precision,
    infraestructura_actualizacion_anio integer,
    infraestructura_es_snapshot boolean,
    infraestructura_temporalidad text,
    infraestructura_uso_recomendado text
);

CREATE TABLE IF NOT EXISTS analytics.modeling_panel (
    alcaldia_id integer,
    tiempo_id integer,
    alcaldia_key text,
    alcaldia_nombre text,
    anio integer,
    target_robos_patrimoniales_total bigint,
    target_robos_log1p double precision,
    share_robos_patrimoniales_sobre_total_delitos double precision,
    share_robo_a_transeunte double precision,
    share_robo_a_negocio double precision,
    share_robo_a_casa_habitacion double precision,
    share_robo_de_vehiculo double precision,
    share_robo_de_accesorios_auto double precision,
    share_robo_del_interior_de_vehiculo double precision,
    mmip_wmean double precision,
    rei_wmean double precision,
    nbi_wmean double precision,
    ccevj_wmean double precision,
    cbdj_wmean double precision,
    csj_wmean double precision,
    ctelj_wmean double precision,
    cenj_wmean double precision,
    ett_wmean double precision,
    casi_wmean double precision,
    cassi_wmean double precision,
    cyt_wmean double precision,
    mercados_total bigint,
    locales_total bigint,
    iluminacion_total bigint,
    iluminacion_promedio double precision,
    residuos_ton_total bigint,
    equipamiento_salud_total bigint,
    equipamiento_educativo_total bigint,
    agua_potable_promedio double precision,
    electricidad_promedio double precision,
    drenaje_promedio double precision,
    total_delitos_fgj bigint,
    n_registros_sociales integer,
    factor_sum bigint,
    infraestructura_actualizacion_anio integer,
    infraestructura_es_snapshot boolean,
    infraestructura_temporalidad text
);

CREATE TABLE IF NOT EXISTS analytics.feature_catalog (
    feature_name text,
    source_dataset text,
    feature_role text,
    data_type text,
    description text,
    leakage_risk text,
    recommended_for_modeling boolean,
    temporal_behavior text,
    notes text
);

