-- Ejecutar desde la raiz del proyecto o ajustar rutas relativas.
-- Los CSV usan UTF-8 y NULL '\N'.

\copy analytics.pobreza_alcaldia_anio (alcaldia_key, alcaldia_nombre, alcaldia_id, anio, tiempo_id, n_registros_sociales, factor_sum, mmip_wmean, rei_wmean, nbi_wmean, ccevj_wmean, cbdj_wmean, csj_wmean, ctelj_wmean, cenj_wmean, ett_wmean, casi_wmean, cassi_wmean, cyt_wmean) FROM 'data/processed/analytics/pobreza_alcaldia_anio.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy analytics.infraestructura_alcaldia (alcaldia_key, alcaldia_nombre, alcaldia_id, colonias_count, infraestructura_actualizacion_anio, infraestructura_es_snapshot, infraestructura_uso_recomendado, ba1_noeqsa_sum, ba8_nomerc_sum, ba8_noloca_sum, ba9_no_gua_sum, ba3_noeqed_sum, resid_ton_sum, alump_sum_total, p_porcelec_avg, r_valelect_avg, p_aguapot_avg, r_val_dren_avg, epr_pob_avg, r_epr_pob_avg, r_resd_ton_avg, alump_mean_avg, r_alump_su_avg, r_alump_mn_avg, s_ri_6_avg, c_ri_6_avg, mercados_total, locales_total, iluminacion_total, iluminacion_promedio, residuos_ton_total, equipamiento_salud_total, equipamiento_educativo_total, agua_potable_promedio, electricidad_promedio, drenaje_promedio) FROM 'data/processed/analytics/infraestructura_alcaldia.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy analytics.delitos_alcaldia_mes_subtipo (alcaldia_key, alcaldia_nombre, alcaldia_id, anio, mes, tiempo_id, subtipo_robo_patrimonial, total_delitos, registros_con_coordenadas, latitud_promedio, longitud_promedio) FROM 'data/processed/analytics/delitos_alcaldia_mes_subtipo.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy analytics.delitos_alcaldia_anio (alcaldia_key, alcaldia_nombre, alcaldia_id, anio, tiempo_id, total_delitos_fgj, total_robos_patrimoniales, target_robos_patrimoniales_total, robo_a_transeunte, robo_a_negocio, robo_a_casa_habitacion, robo_de_vehiculo, robo_de_accesorios_auto, robo_del_interior_de_vehiculo) FROM 'data/processed/analytics/delitos_alcaldia_anio.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy analytics.panel_alcaldia_anio (alcaldia_key, alcaldia_nombre, alcaldia_id, anio, tiempo_id, n_registros_sociales, factor_sum, mmip_wmean, rei_wmean, nbi_wmean, ccevj_wmean, cbdj_wmean, csj_wmean, ctelj_wmean, cenj_wmean, ett_wmean, casi_wmean, cassi_wmean, cyt_wmean, total_delitos_fgj, total_robos_patrimoniales, target_robos_patrimoniales_total, robo_a_transeunte, robo_a_negocio, robo_a_casa_habitacion, robo_de_vehiculo, robo_de_accesorios_auto, robo_del_interior_de_vehiculo, colonias_count, mercados_total, locales_total, iluminacion_total, iluminacion_promedio, residuos_ton_total, equipamiento_salud_total, equipamiento_educativo_total, agua_potable_promedio, electricidad_promedio, drenaje_promedio, infraestructura_actualizacion_anio, infraestructura_es_snapshot, infraestructura_uso_recomendado) FROM 'data/processed/analytics/panel_alcaldia_anio.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy analytics.modeling_panel (alcaldia_id, tiempo_id, alcaldia_key, alcaldia_nombre, anio, target_robos_patrimoniales_total, mmip_wmean, rei_wmean, nbi_wmean, ccevj_wmean, cbdj_wmean, csj_wmean, ctelj_wmean, cenj_wmean, ett_wmean, casi_wmean, cassi_wmean, cyt_wmean, mercados_total, locales_total, iluminacion_total, iluminacion_promedio, residuos_ton_total, equipamiento_salud_total, equipamiento_educativo_total, agua_potable_promedio, electricidad_promedio, drenaje_promedio, total_delitos_fgj, n_registros_sociales, factor_sum, infraestructura_actualizacion_anio, infraestructura_es_snapshot) FROM 'data/processed/analytics/modeling_panel.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy analytics.feature_catalog (feature_name, source_dataset, feature_role, data_type, description, leakage_risk, recommended_for_modeling, temporal_behavior) FROM 'data/processed/analytics/feature_catalog.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
