-- Ejecutar desde la raiz del proyecto o ajustar rutas relativas.
-- Los CSV usan UTF-8 y NULL '\N'.

\copy dw.dim_alcaldia (alcaldia_id, alcaldia_key, alcaldia_nombre, municipio_enigh, cve_ent, entidad_nombre) FROM 'dimensional_schema/dim_alcaldia.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.dim_tiempo (tiempo_id, anio, mes, mes_nombre, trimestre, granularidad) FROM 'dimensional_schema/dim_tiempo.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.dim_colonia (colonia_id, alcaldia_id, colonia_key, colonia_nombre, cve_col) FROM 'dimensional_schema/dim_colonia.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.dim_delito_subtipo (delito_subtipo_id, subtipo_robo_patrimonial, descripcion, es_robo_patrimonial) FROM 'dimensional_schema/dim_delito_subtipo.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.dim_variable_social (variable_social_id, variable_nombre, variable_origen, descripcion, metodo_agregacion, rango_esperado, recomendada_modelado) FROM 'dimensional_schema/dim_variable_social.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.dim_variable_infraestructura (variable_infraestructura_id, variable_nombre, variable_origen, descripcion, metodo_agregacion, actualizacion_anio, temporalidad, recomendada_modelado) FROM 'dimensional_schema/dim_variable_infraestructura.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.dim_fuente_datos (fuente_datos_id, fuente_nombre, fuente_tipo, archivo_origen, carpeta_origen, cobertura_temporal, granularidad_original, granularidad_final, notas_uso) FROM 'dimensional_schema/dim_fuente_datos.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.fact_delitos_generales_alcaldia_anio (alcaldia_id, tiempo_id, fuente_datos_id, total_delitos_fgj, total_robos_patrimoniales, total_no_robos_patrimoniales, share_robos_patrimoniales_sobre_total_delitos) FROM 'dimensional_schema/fact_delitos_generales_alcaldia_anio.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.fact_robos_patrimoniales_alcaldia_mes_subtipo (alcaldia_id, tiempo_id, delito_subtipo_id, fuente_datos_id, total_robos_patrimoniales, registros_con_coordenadas, latitud_promedio, longitud_promedio) FROM 'dimensional_schema/fact_robos_patrimoniales_alcaldia_mes_subtipo.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.fact_robos_patrimoniales_alcaldia_anio (alcaldia_id, tiempo_id, fuente_datos_id, target_robos_patrimoniales_total, robo_a_transeunte, robo_a_negocio, robo_a_casa_habitacion, robo_de_vehiculo, robo_de_accesorios_auto, robo_del_interior_de_vehiculo, target_robos_log1p) FROM 'dimensional_schema/fact_robos_patrimoniales_alcaldia_anio.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.fact_pobreza_alcaldia_anio (alcaldia_id, tiempo_id, fuente_datos_id, n_registros_sociales, factor_sum, mmip_wmean, rei_wmean, nbi_wmean, ccevj_wmean, cbdj_wmean, csj_wmean, ctelj_wmean, cenj_wmean, ett_wmean, casi_wmean, cassi_wmean, cyt_wmean) FROM 'dimensional_schema/fact_pobreza_alcaldia_anio.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.fact_infraestructura_alcaldia (alcaldia_id, snapshot_tiempo_id, fuente_datos_id, infraestructura_actualizacion_anio, infraestructura_es_snapshot, infraestructura_temporalidad, colonias_count, ba1_noeqsa_sum, ba8_nomerc_sum, ba8_noloca_sum, ba9_no_gua_sum, ba3_noeqed_sum, resid_ton_sum, alump_sum_total, alump_mean_avg, p_porcelec_avg, p_aguapot_avg, r_val_dren_avg) FROM 'dimensional_schema/fact_infraestructura_alcaldia.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.fact_infraestructura_colonia (colonia_id, alcaldia_id, snapshot_tiempo_id, fuente_datos_id, infraestructura_actualizacion_anio, infraestructura_es_snapshot, infraestructura_temporalidad, cve_col, ba1_noeqsa, ba8_nomerc, ba8_noloca, ba9_no_gua, ba3_noeqed, resid_ton, alump_sum, alump_mean, p_porcelec, p_aguapot, r_val_dren) FROM 'dimensional_schema/fact_infraestructura_colonia.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
\copy dw.fact_panel_analitico_alcaldia_anio (alcaldia_id, tiempo_id, fuente_datos_id, target_robos_patrimoniales_total, target_robos_log1p, share_robos_patrimoniales_sobre_total_delitos, total_delitos_fgj, n_registros_sociales, factor_sum, mmip_wmean, rei_wmean, nbi_wmean, ccevj_wmean, cbdj_wmean, csj_wmean, ctelj_wmean, cenj_wmean, ett_wmean, casi_wmean, cassi_wmean, cyt_wmean, mercados_total, locales_total, iluminacion_total, iluminacion_promedio, residuos_ton_total, equipamiento_salud_total, equipamiento_educativo_total, agua_potable_promedio, electricidad_promedio, drenaje_promedio, infraestructura_actualizacion_anio, infraestructura_es_snapshot, infraestructura_temporalidad, anio, alcaldia_key, alcaldia_nombre) FROM 'dimensional_schema/fact_panel_analitico_alcaldia_anio.csv' WITH (FORMAT csv, HEADER true, NULL '\N', ENCODING 'UTF8');
